using UnityEngine;

namespace SteeringBehaviors
{
/// <summary>
/// Represents an aggregator that combines goals from child nodes implementing
/// the IPipelineTargeter interface into a single aggregated goal.
/// </summary>
public class PipelineTargeterAggregator : MonoBehaviour
{
    private IPipelineTargeter[] _pipelineTargeters;
    
    /// <summary>
    /// Loads all child nodes implementing the IPipelineTargeter interface.
    /// </summary>
    /// <remarks>
    /// Be aware that order matters. Targeters will be evaluated in the order they are
    /// in the tree. So, they will be evaluated from top to bottom.
    /// </remarks>
    private void LoadPipelineTargeters()
    {
        _pipelineTargeters = GetComponentsInChildren<IPipelineTargeter>();
    }

    private void Start()
    {
        LoadPipelineTargeters();
    }
    
    /// <summary>
    /// Aggregates the goals generated by all child nodes implementing the
    /// IPipelineTargeter interface into a combined goal.
    /// </summary>
    /// <returns>A PipelineGoal object containing the aggregated goal values
    /// derived from the child IPipelineTargeter nodes.</returns>
    public PipelineGoal GetAggregatedGoal(SteeringBehaviorArgs args)
    {
        PipelineGoal aggregatedGoal = new();
        foreach (IPipelineTargeter pipelineTargeter in _pipelineTargeters)
        {
            PipelineGoal targeterGoal = pipelineTargeter.GetGoal(args);
            if (targeterGoal == null) continue;
            aggregatedGoal.UpdateChannels(targeterGoal);
        }
        return aggregatedGoal;
    }
}
}

