
using System.Collections.Generic;
using Tools;
using UnityEngine;

namespace Sensors
{
/// <summary>
/// Represents directional interest values for steering behaviors. Each whisker evaluates
/// alignment with a given ideal velocity to assign a corresponding interest value.
/// </summary>
public class InterestWhiskers : MonoBehaviour
{
    private readonly List<RayEnds> _interestWhiskers = new();
    private readonly List<float> _interests = new();
    
    public int Count => _interestWhiskers.Count;

    /// <summary>
    /// Updates the collection of interest whiskers with new ray endpoints and
    /// initializes their interest values.
    /// </summary>
    /// <param name="interestEnds">A list of <see cref="RayEnds"/> representing the
    /// new set of ray endpoints defining the interest whiskers.</param>
    public void ReloadWhiskers(List<RayEnds> interestEnds)
    {
        _interestWhiskers.Clear();
        _interestWhiskers.AddRange(interestEnds);
        _interests.Clear();
        _interests.AddRange(new float[_interestWhiskers.Count]);
    }

    /// <summary>
    /// Calculates the interest values for each whisker based on the specified
    /// ideal velocity.
    /// </summary>
    /// <param name="idealVelocity">A <see cref="Vector2"/> representing the desired
    /// movement direction in global coordinates, used to compute the alignment with
    /// each whisker's direction.</param>
    public void CalculateInterests(Vector2 idealVelocity)
    {
        // idealVelocity is in global coordinates, while ray ends come in local
        // coordinates.
        int index = 0;
        foreach (RayEnds interestWhisker in _interestWhiskers)
        {
            Vector2 normalizedInterestWhisker = 
                (transform.TransformPoint(interestWhisker.end) - 
                 transform.TransformPoint(interestWhisker.start))
                .normalized;
            _interests[index] = 
                Mathf.Max(0, Vector2.Dot(
                    normalizedInterestWhisker,
                    idealVelocity));
            index++;
        }
    }

    /// <summary>
    /// Retrieves the interest at the specified index, including its value and direction.
    /// </summary>
    /// <param name="index">The zero-based index of the interest to retrieve.</param>
    /// <returns>An <see cref="Interest"/> containing the value and direction
    /// of the specified interest whisker.</returns>
    public Interest GetInterest(int index)
    {
        return new Interest
        {
            value = _interests[index], 
            direction = transform.TransformPoint(_interestWhiskers[index].end) - 
                        transform.TransformPoint(_interestWhiskers[index].start)
        };
    }

    /// <summary>
    /// Retrieves the complete list of interests generated by the interest whiskers.
    /// </summary>
    /// <returns>A list of <see cref="Interest"/> objects representing the interests
    /// calculated for each whisker.</returns>
    public List<Interest> GetInterests()
    {
        List<Interest> interests = new();
        for (int i = 0; i < Count; i++)
        {
            interests.Add(GetInterest(i));
        }
        return interests;
    }
}
}

